[build]
# Run crawler but don't fail the build if it exits non-zero.
# Then run postprocess to assemble /public and sanitize filenames/links.
command = "bash -x build.sh || echo 'WARN: build.sh non-zero, continuing'; bash -x postprocess.sh"
publish = "public"

[build.environment]
WGET_VERSION = "present"
